
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Step into the source tree
          command: 'cd postgres'
      - run:
          name: Debug
          command: 'ls -al'
      - run:
          name: Create build config
          command: './configure'
      - run:
          name: Start building
          command: 'make -j $(nproc)'

