
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Install SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install other dependencies
          command: 'apt-get install -y libreadline-dev'
      - run:
          name: Start building
          command: 'cd ./postgres && ./configure && make -j $(nproc)'

